//Home
export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const SET_EXPANDED_RECORDS = 'SET_EXPANDED_RECORDS';
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';
export const TABLE_HEADER_CLICK = 'TABLE_HEADER_CLICK';
export const SEARCH_MARKETS = 'SEARCH_MARKETS';

export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
//market
export const GET_MARKET_LIST = 'GET_MARKET_LIST';
export const GET_MARKET_CREATED_LIST = 'GET_MARKET_CREATED_LIST';
export const GET_MARKET_DETAIL = 'GET_MARKET_DETAIL';
export const CREATE_MARKET = 'CREATE_MARKET';
export const BOOKMARK_MARKET = 'BOOKMARK_MARKET';
//create market
export const SET_ACTIVE_INDEX = 'SET_ACTIVE_INDEX';
//user
export const ADD_USER = 'ADD_USER';
export const UPDATE_USER_NAME = 'UPDATE_USER_NAME';
export const UPDATE_USER_AVATAR = 'UPDATE_USER_AVATAR';
export const QUERY_USER_INFO = 'QUERY_USER_INFO';
//panel
export const PANEL_SET_ACTIVE_TAB = 'PANEL_SET_ACTIVE_TAB';
export const SET_EXPANDED_WALLET = 'SET_EXPANDED_WALLET';
export const SET_EXPANDED_MARKET = 'SET_EXPANDED_MARKET';
export const SET_EXPANDED_BOOKMARK = 'SET_EXPANDED_BOOKMARK';
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_USER_AVATAR = 'SET_USER_AVATAR';
export const METAMASK_LOGIN = 'METAMASK_LOGIN';
export const METAMASK_ETH_BALANCE = 'METAMASK_ETH_BALANCE';
export const METAMASK_ETH_TRANSACTION = 'METAMASK_ETH_TRANSACTION';
//eth
export const ETH_SUT_BALANCE = 'ETH_SUT_BALANCE';
export const ETH_CREATE_MARKET = 'ETH_CREATE_MARKET';
export const ETH_GET_MARKET_BY_INDEX = 'ETH_GET_MARKET_BY_INDEX';
export const ETH_SET_MARKET_ADDRESS = 'ETH_SET_MARKET_ADDRESS';
export const ETH_GET_CT_BALANCE = 'ETH_GET_CT_BALANCE';
export const ETH_IS_TRADE_ENABLE = 'ETH_IS_TRADE_ENABLE';
export const ETH_GET_MARKET_CREATOR = 'ETH_GET_MARKET_CREATOR';
export const ETH_GET_Total_SUT = 'ETH_GET_Total_SUT';
export const ETH_BID_QUOTE = 'ETH_BID_QUOTE';
export const ETH_ASK_QUOTE = 'ETH_ASK_QUOTE';
//dispute
export const DISPUTE_MARKET_STATE = 'DISPUTE_MARKET_STATE';
export const DISPUTE_NEXT_FLAGGABLE_DATE = 'DISPUTE_NEXT_FLAGGABLE_DATE';
export const DISPUTE_CREATE = 'DISPUTE_CREATE';
export const DISPUTE_FLAGGING_PERIOD = 'DISPUTE_FLAGGING_PERIOD';
export const DISPUTE_JUROR_VOTE = 'DISPUTE_JUROR_VOTE';
export const DISPUTE_JUROR_VOTE_DONE = 'DISPUTE_JUROR_VOTE_DONE';
export const DISPUTE_DONE = 'DISPUTE_DONE';
export const DISPUTE_JUROR_LIST = 'DISPUTE_JUROR_LIST';
export const DISPUTE_JUROR_VOTES = 'DISPUTE_JUROR_VOTES';
export const DISPUTE_APPEAL_ROUND = 'DISPUTE_APPEAL_ROUND';
export const DISPUTE_APPEALING_PERIOD = 'DISPUTE_APPEALING_PERIOD';
export const DISPUTE_DO_APPEAL = 'DISPUTE_DO_APPEAL';
export const DISPUTE_MARKET_DISSOLVE = 'DISPUTE_MARKET_DISSOLVE';
//proposed
export const PROPOSED_DO_PROPOSED = 'PROPOSED_DO_PROPOSED';
export const PROPOSED_CURRENT_AMOUNT = 'PROPOSED_CURRENT_AMOUNT';
export const PROPOSED_AMOUNT = 'PROPOSED_AMOUNT';
export const PROPOSED_VOTING_PERIOND = 'PROPOSED_VOTING_PERIOND';
export const PROPOSED_DO_VOTE = 'PROPOSED_DO_VOTE';
export const PROPOSED_JURORS = 'PROPOSED_JURORS';
export const PROPOSED_VOTES = 'PROPOSED_VOTES';
export const PROPOSED_VOTE_DONE = 'PROPOSED_VOTE_DONE';
//ipfs
export const IPFS_POST_STRING = 'IPFS_POST_STRING';
export const IPFS_GET_FILE = 'IPFS_GET_FILE';
export const IPFS_POST_FILE = 'IPFS_POST_FILE';
//bigchain
export const BIGCHAIN_GET = 'BIGCHAIN_GET';
export const BIGCHAIN_PUT = 'BIGCHAIN_PUT';
export const BIGCHAIN_SEARCH = 'BIGCHAIN_SEARCH';
export const BIGCHAIN_OWNER_SEARCH = 'BIGCHAIN_OWNER_SEARCH';





