export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
//MATEMASK
export const MATEMASK_STATUS = 'MATEMASK_STATUS';
export const MATEMASK_LOGIN = 'MATEMASK_LOGIN';
export const MATEMASK_ETH_BALANCE = 'MATEMASK_ETH_BALANCE';
export const MATEMASK_ETH_TRANSACTION = 'MATEMASK_ETH_TRANSACTION';
//ETH
export const ETH_SUT_BALANCE = 'ETH_SUT_BALANCE';
export const ETH_CREATE_MARKET = 'ETH_CREATE_MARKET';
export const ETH_GET_MARKET_BY_INDEX = 'ETH_GET_MARKET_BY_INDEX';
export const ETH_SET_MARKET_ADDRESS = 'ETH_SET_MARKET_ADDRESS';
export const ETH_GET_CT_BALANCE = 'ETH_GET_CT_BALANCE';
export const ETH_IS_TRADE_ENABLE = 'ETH_IS_TRADE_ENABLE';
export const ETH_GET_MARKET_CREATOR = 'ETH_GET_MARKET_CREATOR';
export const ETH_GET_Total_SUT = 'ETH_GET_Total_SUT';
export const ETH_BID_QUOTE = 'ETH_BID_QUOTE';
export const ETH_ASK_QUOTE = 'ETH_ASK_QUOTE';
//ipfs
export const IPFS_POST_STRING = 'IPFS_POST_STRING';
export const IPFS_GET_FILE = 'IPFS_GET_FILE';
export const IPFS_POST_FILE = 'IPFS_POST_FILE';
//bigchain
export const BIGCHAIN_GET = 'BIGCHAIN_GET';
export const BIGCHAIN_PUT = 'BIGCHAIN_PUT';
export const BIGCHAIN_SEARCH = 'BIGCHAIN_SEARCH';
export const BIGCHAIN_OWNER_SEARCH = 'BIGCHAIN_OWNER_SEARCH';





